### ISSUE TITLE
question: node versions supported

### ISSUE THREAD

**Issue by jjangga0214** [CyriacBr/get-pty-output#2]
Hi!

Thank you so much for this great project.
Is this right that every major nodejs version >=10 is supported?
(e.g. 10.x, 11.x, 12.x, .... , 18.x, 19.x, 20.x)

https://github.com/CyriacBr/get-pty-output/blob/c0d5266bb8dfedd855a7bbceabdcf2a12d1c1548/package.json#L32-L33

I want to use `get-pty-output` in my open-source project. 
But my project should support **every** recent nodejs versions.
(e.g. `node>=16` : 16.x, 17.x, 18.x, 19.x, 20.x)

What's more, once a new nodejs version is released(e.g. 21.x(future)), my package should become ready for the runtime as soon as possible.

Would it be possible?

This is just asking for making sure before publishing my public npm package.

Thanks again!

**Comment by CyriacBr** [comment]
Yes, since this package is built using `napi-rs`, every major since v10 is supported, as you can see here: https://napi.rs/#support-matrix.  
If a new node major ships and `napi-rs` needs adjustments to support it, then you'd have to wait for me to update `get-pty-output`, and you'd have to update your package as well.
